language: erlang
script: "make compile && rm -rf .git && make test"
notifications:
  irc: "irc.freenode.org#elixir-lang"
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
otp_release:
  - R16B02
  - R16B01
  - R16B
